devel: Support 'update_nocheck' target.

diff --git a/devel b/devel
--- a/devel
+++ b/devel
@@ -213,14 +213,19 @@ mbd_purge()
 
 mbd_update()
 {
-	set +e
-	(
+	if [ "${1}" = "nocheck" ]; then
+		export DEB_BUILD_OPTIONS+=" nocheck"
+	else
+		# Run mbd_check, but with option to continue on error
+		set +e
+		(
+			set -e
+			mbd_check
+		)
+		ret=$?
+		[ ${ret} -eq 0 ] || read -p "Check failed. Continue anyway? [R]" dummy
 		set -e
-		mbd_check
-	)
-	ret=$?
-	[ ${ret} -eq 0 ] || read -p "Check failed. Continue anyway? [R]" dummy
-	set -e
+	fi
 
 	_head "Checking changelog (must be unchanged)..."
 	git diff-index --exit-code HEAD debian/changelog
