devel: Add pre-code to purge that tries hard to remove lvm leftovers before actually purging dir.

diff --git a/devel b/devel
--- a/devel
+++ b/devel
@@ -21,6 +21,20 @@ mbd_clear()
 mbd_purge()
 {
 	_head "Purging ${MBD_HOME}"
+
+	# Try hard to clean up any lvm loop leftovers
+	for n in $(schroot -l -a 2>/dev/null); do schroot -c ${n} -e || true; done
+	for lv in $(sudo lvdisplay | grep 'LV Name.*/dev/mini-buildd-loop-.\+/mini-buildd-.\+-.\+' | rev | cut -d' ' -f1 | rev); do
+		echo lv=${lv}
+		sudo lvremove --verbose --force "${lv}" || true
+	done
+	for vg in $(sudo vgdisplay | grep 'VG Name.*mini-buildd-loop-.\+-.\+$'| rev | cut -d' ' -f1 | rev); do
+		echo vg=${vg}
+		sudo vgremove --verbose --force ${vg} || true
+	done
+	sudo losetup --verbose --detach /dev/loop0 || true
+
+	# Purge and re-setup
 	[ ! -e "${MBD_HOME}" ] || rm -r "${MBD_HOME}"
 	mkdir -v -p "${MBD_HOME}"
 }
