Cosmetic fixes in UploadDSP check.

diff --git a/lib/mbd-qa-check b/lib/mbd-qa-check
--- a/lib/mbd-qa-check
+++ b/lib/mbd-qa-check
@@ -123,15 +123,16 @@ mbdQACheckUploadDSP()
 		if ! ${MBD_TMP_SCP} -p ${mbdParseCF_files} "${mbdParseBH_host}:${bDir}/"; then
 			echo "E: Error uploading DSP to build host ${mbdParseBH_host}."
 			retval=2
-		fi
-		echo "I: Files from changes uploaded: ${mbdParseCF_files}."
-
-		if [ ! -e "${mbdParseCF_orig_tarball}" -a -e "${repOrig}" ]; then
-			if ! ${MBD_TMP_SCP} -p "${repOrig}" "${mbdParseBH_host}:${bdir}/"; then
-				echo "E: Error uploading orig tarball from repo."
-				retval=2
+		else
+			echo "I: Files from changes uploaded: ${mbdParseCF_files}."
+			if [ ! -e "${mbdParseCF_orig_tarball}" -a -e "${repOrig}" ]; then
+				if ! ${MBD_TMP_SCP} -p "${repOrig}" "${mbdParseBH_host}:${bdir}/"; then
+					echo "E: Error uploading orig tarball from repo."
+					retval=2
+				else
+					echo "I: Orig tarball from repo uploaded: ${mbdParseCF_orig_tarball}"
+				fi
 			fi
-			echo "I: Orig tarball from repo uploaded: ${mbdParseCF_orig_tarball}"
 		fi
 	done
 	return ${retval}
