* Update all lib/*.

diff --git a/lib/mbd-qa-check b/lib/mbd-qa-check
--- a/lib/mbd-qa-check
+++ b/lib/mbd-qa-check
@@ -116,16 +116,16 @@ mbdQACheckUploadDSP()
 	local repOrig="${MBD_HOME}/rep/${mbdParseCF_dist}/${mbdParseCF_orig_tarball}"
 
 	for arch in `echo "${mbd_archs}" | tr -d ","`; do
-		local bldhost="mbd_bldhost_${arch}"
-		echo "I: Uploading for ${!bldhost}."
+		mbdParseBH "${arch}"
+		echo "I: Uploading for ${mbdParseBH_host}."
 
-		if ! (${MBD_TMP_SSH} "${!bldhost}" mkdir -p -v "${bDir}" && ${MBD_TMP_SCP} -p ${mbdParseCF_files} "${!bldhost}:${bDir}/"); then
-			echo "E: Error uploading DSP to build host ${!bldhost}."
+		if ! (${MBD_TMP_SSH} "${mbdParseBH_host}" mkdir -p -v "${bDir}" && ${MBD_TMP_SCP} -p ${mbdParseCF_files} "${mbdParseBH_host}:${bDir}/"); then
+			echo "E: Error uploading DSP to build host ${mbdParseBH_host}."
 			retval=2
 		else
 			echo "I: Files from changes uploaded: ${mbdParseCF_files}."
 			if [ ! -e "${mbdParseCF_orig_tarball}" -a -e "${repOrig}" ]; then
-				if ! ${MBD_TMP_SCP} -p "${repOrig}" "${!bldhost}:${bDir}/"; then
+				if ! ${MBD_TMP_SCP} -p "${repOrig}" "${mbdParseBH_host}:${bDir}/"; then
 					echo "E: Error uploading orig tarball from repo."
 					retval=2
 				else
@@ -216,7 +216,8 @@ mbdQACheckDownloadDBP()
 mbdRunCheck()
 {
 	if mbd_opt_given r; then
-		${MBD_TMP_SSH} `mbdGetBH "${MBD_TMP_ARCH}"` ${MBD_LIB}/mbd-qa-check -c "`mbd_opt_get c`" -a "${MBD_TMP_ARCH}" -q "${check}" -I "`mbd_opt_get I`"
+		mbdParseBH "${MBD_TMP_ARCH}"
+		${MBD_TMP_SSH} ${mbdParseBH_host} ${MBD_LIB}/mbd-qa-check -c "`mbd_opt_get c`" -a "${MBD_TMP_ARCH}" -q "${check}" -I "`mbd_opt_get I`"
 	else
 		mbdQACheck${1}
 	fi
