comsetics: Fix name.

diff --git a/lib/mbd-qa-check b/lib/mbd-qa-check
--- a/lib/mbd-qa-check
+++ b/lib/mbd-qa-check
@@ -125,18 +125,18 @@ mbdQACheckUploadDSP()
 	local repOrig="${MBD_HOME}/rep/${mbdParseCF_dist}/${mbdParseCF_orig_tarball}"
 
 	for arch in `mbdD2SList "${mbd_archs}"`; do
-		mbdParseBH "${arch}"
-		local buildDir="bld/builds/`mbdBId2BDir "${mbdParseBH_arch}" "${MBD_TMP_BUILDID}"`"
+		mbdParseArch "${arch}"
+		local buildDir="bld/builds/`mbdBId2BDir "${mbdParseArch_arch}" "${MBD_TMP_BUILDID}"`"
 
-		echo "I: Uploading for ${mbdParseBH_host}/${mbdParseBH_arch}."
+		echo "I: Uploading for ${mbdParseArch_host}/${mbdParseArch_arch}."
 
-		if ! (${MBD_TMP_SSH} "${mbdParseBH_host}" mkdir -p -v "${buildDir}" && ${MBD_TMP_SCP} -p ${mbdParseCF_files} "${mbdParseBH_host}:${buildDir}/"); then
-			echo "E: Error uploading DSP to build host ${mbdParseBH_host}."
+		if ! (${MBD_TMP_SSH} "${mbdParseArch_host}" mkdir -p -v "${buildDir}" && ${MBD_TMP_SCP} -p ${mbdParseCF_files} "${mbdParseArch_host}:${buildDir}/"); then
+			echo "E: Error uploading DSP to build host ${mbdParseArch_host}."
 			retval=2
 		else
 			echo "I: Files from changes uploaded: ${mbdParseCF_files}."
 			if [ ! -e "${mbdParseCF_orig_tarball}" -a -e "${repOrig}" ]; then
-				if ! ${MBD_TMP_SCP} -p "${repOrig}" "${mbdParseBH_host}:${buildDir}/"; then
+				if ! ${MBD_TMP_SCP} -p "${repOrig}" "${mbdParseArch_host}:${buildDir}/"; then
 					echo "E: Error uploading orig tarball from repo."
 					retval=2
 				else
@@ -184,11 +184,11 @@ mbdQACheckBuild()
 	local retval=0
 	local lf="${MBD_TMP_CF}.build"
 	local chroot="mbd-${mbdParseCF_dist}-${MBD_TMP_ARCH}"
-	mbdParseBH "${MBD_TMP_ARCH}"
+	mbdParseArch "${MBD_TMP_ARCH}"
 
 	# sbuild_mode is set to "user"; sbuild failure means build failure, or nothing to build for that arch.
-	if sbuild --dist="${mbdParseCF_dist}" --arch="${MBD_TMP_ARCH}" --chroot="${chroot}" ${mbdParseBH_options} "${mbdParseCF_package}.dsc" >"${lf}" 2>&1; then
-		echo "I: Built successful for arch=${MBD_TMP_ARCH} [${mbdParseBH_options}]."
+	if sbuild --dist="${mbdParseCF_dist}" --arch="${MBD_TMP_ARCH}" --chroot="${chroot}" ${mbdParseArch_options} "${mbdParseCF_package}.dsc" >"${lf}" 2>&1; then
+		echo "I: Built successful for arch=${MBD_TMP_ARCH} [${mbdParseArch_options}]."
 	else
 		# @hack: If this package has no packages to be built for this arch, this is ok, and we get:
 		if grep -i "${MBD_TMP_ARCH}.*not in arch list.*skipping" ${lf}; then
@@ -224,8 +224,8 @@ mbdQACheckDownloadDBP()
 mbdRunCheck()
 {
 	if mbd_opt_given r; then
-		mbdParseBH "${MBD_TMP_ARCH}"
-		${MBD_TMP_SSH} ${mbdParseBH_host} ${MBD_LIB}/mbd-qa-check -c "`mbd_opt_get c`" -a "${MBD_TMP_ARCH}" -q "${check}" -I "`mbd_opt_get I`"
+		mbdParseArch "${MBD_TMP_ARCH}"
+		${MBD_TMP_SSH} ${mbdParseArch_host} ${MBD_LIB}/mbd-qa-check -c "`mbd_opt_get c`" -a "${MBD_TMP_ARCH}" -q "${check}" -I "`mbd_opt_get I`"
 	else
 		mbdQACheck${1}
 	fi
