* mbd-remove-pkg:     - Add interactive security check that this is experimental.     - Actually install this tool to -rep package.

diff --git a/lib/mbd-remove-pkg b/lib/mbd-remove-pkg
--- a/lib/mbd-remove-pkg
+++ b/lib/mbd-remove-pkg
@@ -1,5 +1,7 @@
 #!/bin/sh -e
 
+exp_check()
+{
 # Showstoppers:
 #
 # BUG: mini-dinstall only keeps latest changes file. see TODO.
@@ -7,14 +9,23 @@
 # Missing 0.7.x:
 #  - stop mbd, remove db files, regenerate indexes.
 #
+	local a
+	read -p"WARNING: This is EXPERIMENTAL. Use only for testing. Continue (y/N)? " a
+	if [ "${a}" != "y" ]; then
+		echo "Aborting..." >&2
+		exit 199
+	fi
+}
 
-#. `dirname $0`/mbd-common.sh
-. /usr/lib/mini-buildd/mbd-common.sh
+. `dirname $0`/mbd-common.sh
 
 mbd_opt_init "Mini-buildd: EXPERIMENTAL: DONT USE THIS. Remove a package from the repository."
 mbd_opt_add "p:" "Source package with version in the form package_version."
 mbd_opt_add "Y:" "Don't ask before removing."
 mbd_opt_parse "$@"
+
+# EXPERIMENTAL CHECK!
+exp_check
 
 PACKAGE=`mbd_opt_get p`
 
